import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { AppSidebar } from "@/components/global/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { SidebarLayout } from "@/components/global/sidebar-layout";
import { UserProvider } from '@auth0/nextjs-auth0/client';



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
        > 

            <SidebarProvider>
              <div className="flex flex-1 overflow-hidden">

                <AppSidebar />
                <SidebarLayout>{children}</SidebarLayout>
              </div>
            </SidebarProvider>

        </body>
      </UserProvider>
    </html>
  );
}
